I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 166, in script
    show rune curious at left
Exception: Image 'rune' does not accept attributes 'curious'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 166, in script
    show rune curious at left
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\display\image.py", line 722, in _duplicate
    args.extraneous()
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'rune' does not accept attributes 'curious'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Fantasy Ren'py GUI template 1.0
Fri Nov  1 00:39:16 2024
